language: rust
cache: cargo

stages:
  - formatting
  - test
  - lint
jobs:
  include:
    - name: check rustfmt
      stage: formatting
      os: linux
      rust: stable
      before_script: rustup component add rustfmt
      script: cargo fmt -- --check

    - stage: test
      os: linux
      rust: stable
      before_script: 'sudo hostname eyjafjallajökull'
      script: cargo test --verbose -- --ignored
    - stage: test
      os: osx
      rust: stable
      before_script: 'sudo hostname eyjafjallajökull'
      script: cargo test --verbose -- --ignored
    - stage: test
      os: windows
      rust: stable
      before_script: ''
      script: cargo test --verbose

    - stage: test
      os: linux
      rust: beta
      script: cargo test --verbose
    - stage: test
      os: linux
      rust: nightly
      script: cargo test --verbose

    - stage: lint
      os: linux
      rust: stable
      before_script: rustup component add clippy
      script: cargo clippy --all-targets
    - stage: lint
      os: windows
      rust: stable
      before_script: rustup component add clippy
      script: cargo clippy --all-targets
