language: rust
cache: cargo

stages:
  - formatting
  - test
  - lint
jobs:
  include:
    - name: check rustfmt
      stage: formatting
      os: linux
      rust: stable
      before_script: rustup component add rustfmt
      script: cargo fmt -- --check

    - stage: test
      os: linux
      rust: stable
    - stage: test
      os: osx
      rust: stable

    - stage: test
      os: linux
      rust: beta
    - stage: test
      os: linux
      rust: nightly

    - stage: lint
      os: linux
      rust: stable
      before_script: rustup component add clippy
      script: cargo clippy --all-targets
