name: CI

on:
  push:
    # Don't build tags; that's redundant with pushes to main normally.
    tags-ignore: '*'
    # Only build main, for all other branches rely on pull requests.  This
    # avoids duplicate builds for pull requests.
    branches: main
    # Don't build for trivial changes
    paths-ignore:
      - '*.md'
      - 'LICENSE'
  pull_request:


jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: EmbarkStudios/cargo-deny-action@v1

  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust:
          # Our minimal supported version
          - '1.64.0'
          # The standard Rust version
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - run: cargo test
      # Run tests with fixed hostname on Unix systems
      - run: sudo hostname hostname-for-testing
        if: "!contains(matrix.os, 'windows')"
      - if: "!contains(matrix.os, 'windows')"
        run: cargo test -- --ignored
      - if: matrix.rust == 'stable'
        run: cargo clippy --all-targets
      - run: cargo doc
