name: CI

on: [push]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  cargo-deny:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: EmbarkStudios/cargo-deny-action@v1

  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust:
          # Our minimal supported version
          - '1.56.0'
          # The standard Rust version
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - run: cargo test
      # Run tests with fixed hostname on Unix systems
      - run: sudo hostname hostname-for-testing
        if: "!contains(matrix.os, 'windows')"
      - if: "!contains(matrix.os, 'windows')"
        run: cargo test -- --ignored
      - if: matrix.rust == 'stable'
        run: cargo clippy --all-targets
